### ISSUE TITLE
Setup issue: las_param.go:221:9: undefined: xlib.StrHash

### ISSUE THREAD

**Issue by dcslagel** [softlandia/glasio#9]
@softlandia,

I tried these install steps and failed on `las_param.go:221:9: undefined: xlib.StrHash`.

```bash
go get -u github.com/softlandia/cpd
go install github.com/softlandia/cpd

go get -u github.com/softlandia/xlib
go install github.com/softlandia/xlib

go get -u github.com/softlandia/glasio
```
Output:
```bash
# github.com/softlandia/glasio
src/github.com/softlandia/glasio/las_param.go:221:9: undefined: xlib.StrHash
src/github.com/softlandia/glasio/las_param.go:231:9: undefined: xlib.StrHash
```

My version of GO is `go1.14.2`. Could someone else give it a try to verify whether the issue is only with my configuration or if others get the failure too?

Thank you,
DC

**Comment by softlandia** [comment]
I update xlib

you need to delete existing folder
softlandia/xlib
softlandia/glasio

and try again
go get github.com/softlandia/xlib
then
go get github.com/softlandia/glasio

please send result

**Comment by dcslagel** [comment]
I followed your instructions and successfully installed golasio.

Next, I will try building and running simple and repaire.

Thank you,
DC
